################################################################################################################################################################

# @project        Open Space Toolkit ▸ Mathematics
# @file           .travis.yml
# @author         Lucas Brémond <lucas@loftorbital.com>
# @license        Apache License 2.0

################################################################################################################################################################

branches:
  only:
    - /^\d+\.\d+(\.\d+)?(-\S*)?$/
    - master
    - dev

dist: xenial

os:
  - linux

services:
  - docker

language: cpp

env:
  global:
    - LANG="en_US.UTF-8"

stages:
  - build
  - test
  - name: deploy
    if: tag =~ ^\d+\.\d+(\.\d+)?(-\S*)?$

before_script:
  - echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin

jobs:
  include:
    - stage: build
      name: "Image Building"
      script:
        - make build-development-images
        - make deploy-development-images

    - stage: test
      name: "Unit Testing"
      script:
        - make test-unit-cpp-debian
        - make test-unit-python-debian

    - stage: test
      name: "Coverage Analysis"
      script:
        - make deploy-coverage-cpp-results

    - stage: deploy
      name: "Image Deployment"
      script:
        - make deploy-images

    - stage: deploy
      name: "Documentation Deployment"
      script:
        - make deploy-documentation

    - stage: deploy
      name: "Package Deployment"
      script:
        - make build-packages
      before_deploy:
        - echo "Deploying packages to GitHub Releases..."
      deploy:
        - provider: releases
          token: ${GITHUB_API_KEY}
          file_glob: true
          file:
            - ./packages/cpp/*
            - ./packages/python/*
          on:
            branch: master
            tags: true
      after_deploy:
        - echo "Deploying Python package to PyPI..."
        - make deploy-packages-python

################################################################################################################################################################
